#!/bin/sh
### BEGIN INIT INFO
# Provides: CRATER
# Required-Start: $remote_fs $syslog $dhcpcd
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 
# Short-Description: CRATER
### END INIT INFO

case "$1" in
	start)
		echo "Starting CRATER"
		/home/pi/CRATER/listener.py &
		;;
	stop)
		pkill python
		;;
	reload|force-reload)
		pkill python
		/home/pi/CRATER/listener.py &
		;;
	restart|try-restart)
		pkill python
		/home/pi/CRATER/listener.py &
		;;
esac

exit 0
